### ISSUE TITLE
'vireo/config.h' file not found

### ISSUE THREAD

**Issue by giulianoc** [twitter/vireo#12]
Hi,
  I was testing helloworld.cpp outside of the video directory and I got the following
  error:

/Users/multi/GestioneProgetti/Development/vireo/vireoBinaries/include/vireo/dependency.hpp:28:10: fatal error: 'vireo/config.h' file not found
#include "vireo/config.h"

  I guess, since 'vireo/config.h' is included from 'vireo/dependency.hpp', I guess 'vireo/config.h'
  has to be installed during the 'make install' command.

  Do you agree?

  To solve this issue I copied manually config.h into the vireo installation directory. 

  Best regards
    Giuliano

**Comment by canbal** [comment]
Thanks for pointing this out. Yes, this indeed is a bug. This shoudl fix it for you. https://github.com/twitter/vireo/compare/config?expand=1

Can you check and confirm?

**Comment by canbal** [comment]
fixed in https://github.com/twitter/vireo/pull/15
