### ISSUE TITLE
so what was wrong with gstreamer ?

### ISSUE THREAD

**Issue by kapouer** [twitter/vireo#13]
it would be very instructive to get some information in the README about how vireo compares to other existing frameworks. Being able to understand the pros and cons is a decision maker.

**Comment by canbal** [comment]
I don't know if README is a proper place to discuss other projects, but I agree a comparison would be useful. I personally don't have much experience with gstreamer so the comparison will have to be driven by the community. If this is something you can help with, it would be very helpful.
