### ISSUE TITLE
Debug information option for the vireo and l-smash binaries

### ISSUE THREAD

**Issue by giulianoc** [twitter/vireo#17]
Hi,
  I'm having a crash and I'm doing some debugging...

  Anyway, it would be good if vireo and l-smash would have the compile option to set debug information
  in his binaries.

  Because of that, inside the vireo/vireo/configure.ac, I added the following option to add debug information:
AC_ARG_ENABLE(debug,
AS_HELP_STRING([--enable-debug], 
               [enable debugging, default: no]), 
[case "${enableval}" in    
             yes) debug=true ;;
             no)  debug=false ;;
             *)   AC_MSG_ERROR([bad value ${enableval} for --enable-debug]) ;;
esac],
[debug=false])  
AM_CONDITIONAL(DEBUG, test x"$debug" = x"true")

  Is it possible
  1. to add the above option/code in the github release
  2. to make same change in configure of the l-smash project

  Best regards
    Giuliano

**Comment by canbal** [comment]
Please make the proposed change to configure.ac and submit a PR. Adding a debug option to configure sounds like a good idea. Closing the issue for now, let's continue the discussion on the PR.

You'll have to submit a PR to l-smash project separately, that project is not maintained by our team.
