### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [twitter/vireo#6]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [ExifReader](https://github.com/twitter/vireo/blob/6c4d577e6414671615cb507e48145855be6648a0/imagecore/formats/exif/exifreader.cpp#L41 "Destructor for ExifReader")
- [ResizeCommand::performResize](https://github.com/twitter/vireo/blob/6c4d577e6414671615cb507e48145855be6648a0/imagetool/commands/resize.cpp#L236 "ResizeCommand::performResize function")
- [ResizeCropOperation](https://github.com/twitter/vireo/blob/6c4d577e6414671615cb507e48145855be6648a0/imagecore/image/resizecrop.cpp#L55 "Destructor for ResizeCropOperation")

**Comment by canbal** [comment]
Feel free to send a pull request for it. Closing this issue since we probably won't have the bandwidth to get to this ourselves.
